### ISSUE TITLE
[MAIL#1] Observation.code.coding enthält einen fixedValue für .code

### ISSUE THREAD

**Issue by cybernop** [medizininformatik-initiative/kerndatensatzmodul-PathologieBefund#107]
R. Franke:
> Observation.code.coding enthält einen fixedValue für .code, allerdings keinen Wert für .system, welches zusätzlich nur eine optionale Angabe ist. 
> Es handelt sich offensichtlich um einen LOINC, jedoch ist die existierende Standard-Binding-Strength lediglich ein "example".

**Comment by ThomasDeBe** [comment]
Ich verstehe es so, dass das umgesetzt wurde. Case closed!
