### ISSUE TITLE
[SIMPLIFIER#2280] Prostate tru-cut biopsy sample (specimen)

### ISSUE THREAD

**Issue by cybernop** [medizininformatik-initiative/kerndatensatzmodul-PathologieBefund#109]
https://simplifier.net/medizininformatikinitiative-modulpathologie/ex-mii-patho-specimen-a/~issues/2280

Gunter Haroske
> Der Name sollte geändert werden in "HE-stained slide from Prostate tru-cut biopsy sample (specimen)".
Der Identifier sollte sein: "E12345_21-A1-1HE".
Der type sollte sein: "787150001 |Stained slide of tissue section (specimen)|".
Eine Referenz auf die Elternprobe "E12345_21-A1" (der Paraffinblock) sollte eingefügt werden.
Die extensions bei Processing sind fehl am Platz
Das zweite Processing braucht zwei Additiv-Elemente mit References auf die Substances "12710003 |Hematoxylin stain (substance)|" und "763042003 |Eosin Y (substance)|". Die Substance "Neutral-buffered formalin" ist hier fehl am Platz.

**Comment by cybernop** [comment]
TODO: Beispiele anpassen

**Comment by ThomasDeBe** [comment]
Sollte bereits angepasst sein. Case closed!
