### ISSUE TITLE
[SIMPLIFIER#2345] Typo: Beschreibung Modul Pathologie-Befund

### ISSUE THREAD

**Issue by cybernop** [medizininformatik-initiative/kerndatensatzmodul-PathologieBefund#115]
https://simplifier.net/medizininformatikinitiative-modulpathologie/~issues/2345

Patrick Jolo
> "Im Text Abbildung in Art-Decor sollte Pathologisch-anatomischen Begutachtungen das ""P"" kleingeschrieben werden,
>
> Im Text fehlt zwischen auch und ob ein komma: Zum klinischen Auftrag sowie zu den einzelnen Untersuchungen werden jeweils verschiedene Daten erfasst, unter anderem auch, ob es sich um vorläufige oder abschließenden Untersuchungsbefunde handelt (Status) und verschiedene im Kontext wichtige Zeitpunkte."

**Comment by ByteGnome** [comment]
Komma hinzugefügt
