### ISSUE TITLE
[SIMPLIFIER#2352] (abstract) SD MII Patho Section Grouper Must-Support

### ISSUE THREAD

**Issue by cybernop** [medizininformatik-initiative/kerndatensatzmodul-PathologieBefund#117]
Patrick Jolo
> Die Liste aller Must-Support Datenelemente ist fehlerhaft:
>
> Observation.id: Fehlt in Snapshot also kein Must-Support
Observation.text: Fehlt in Snapshot also kein Must-Support
Observation.meta: Fehlt in Snapshot also kein Must-Support
Observation.partOf: Kein Must-Support
Observation.issued: Kein Must-Support
Observation.performer: Kein Must-Support
Observation.dataAbsentReason: Kein Must-Support
Observation.note: Kein Must-Support
Observation.bodySite: Fehlt in der Liste
Observation.component: Kein Must-Support

**Comment by ByteGnome** [comment]
Wird im [Zulip-Chat](https://chat.fhir.org/#narrow/stream/179307-german.2Fmi-initiative/topic/.5BPATHO.5D.20.28abstract.29.20SD.20MII.20Patho.20Section.20Grouper.20Must-Suppor) weiter besprochen
