### ISSUE TITLE
Beschreibung zu Narrative Extensions zum IG hinzufügen

### ISSUE THREAD

**Issue by ByteGnome** [medizininformatik-initiative/kerndatensatzmodul-PathologieBefund#122]
Wie im [Issue#2361](https://simplifier.net/medizininformatikinitiative-modulpathologie/~issues/2361) besprochen, sollen Erläuterungen zu orginalText und narrativeLink im IG ergänzt werden.

**Comment by ThomasDeBe** [comment]
Case closed!
