### ISSUE TITLE
Vorschläge V2025 Prof Haroske

### ISSUE THREAD

**Issue by ThomasDeBe** [medizininformatik-initiative/kerndatensatzmodul-PathologieBefund#159]
In Nachbetrachtung unserer VK am 9.10. habe ich einige Vorschläge für das Release 2024 des IG Pathobefundberichts zusammengestellt, die ich Ihnen gern zur Diskussion vorschlagen möchte:

1. Erstellung eines Profils PathoBundle, einschließlich der Erläuterungen aus dem HL7 Europe Labreport.
2. PathoComposition um eine section für die Einbindung eines kompletten MolGenBefundberichts.
3. Grouper für Additional specified observations anpassen für die Einbindung von Observations aus einem MolGenBefundbericht.
4. Anpassung von PathoSpecimen an das aktuelle Bioproben-Profil, außerdem Specimen.feature aus R5 per extension einbinden (lt. Vorschlag von Thomas).
5. In PathoServiceRequest SupportingInfo explizit auf die auch mögliche Verwendung von Observations hinweisen.
6. PathoReport code.coding.code mit einem neuen VS (preferred) versehen, der auch die Abfassung strukturierter Befunde mit rein narrativen Inhalt nicht ausschließt. Dazu würden gehören:
- 60568-3
- 11526-1
- 11529-5
- 33716-2
- 50398-7
- 47528-5
- 47527-7
- 18743-5
7. In der Beschreibung der Grouper observations klären, wie und wo Narrative Inhalte abgebildet werden. Als Value.string? Anders?

**Comment by ThimoHoelter** [comment]
1. Ist in der Composition nicht abgedeckt, muss im EU-LapReport nachgesehen werden.
2. Zur Diskussion ins nächste Meeting. Referenz vs. Einbindung sollte geklärt werden
3. Zur Diskussion ins nächste Meeting. Zusätzliche Einbindungen in den Pathobefund notwendig? Kompatibel?
4. https://simplifier.net/medizininformatikinitiative-modulbiobank/profilespecimenbioprobecore + Extension R5 Specimen.feature
5. Gute Idee. Name für Slice steht zur Diskussion.
6. Weiteres Report-Profil für narrative Befunde?
7. IG-Auszug "Der Text (Narrative) dieser "Sections" wird im Observation.text-Element dargestellt. Es besteht außerdem die Möglichkeit die FHIR Core Extensions [original Text](http://hl7.org/fhir/r4/extension-originaltext.html) oder [narrative Link](http://hl7.org/fhir/r4/extension-narrativelink.html) zu nutzen, um den "narrativen" mit dem strukturierten Part mittels HTML-Tags zu verbinden. Für weitere Informationen zur richtigen Anwendung beider Extensions siehe.." https://simplifier.net/guide/mii-ig-pathologie/TechnischeImplementierung-FHIRProfile-abstract-MII-PR-Patho-Section-Grouper?version=current
.text scheint in Erben vom SectionGrouper nicht korrekt gerendert. Ggfs. extra MS einfügen.
8. Vorschlag: Profilierung von specimen.identifier sieihe ServiceRequest (PLAC & FILL)
9. ListItem.category Slice für "problem-list-item" erstellen
10. Composition ISIK Vererbung aktualisieren
11. Notwendigkeit PathoFinding.value zu erweitern? Wenn ja, warum?
12. PathoFinding.code.coding Slices für LOINC und Snomed erstellen.
13. Simplifierseite & IG-Seite Text updaten/ Typos ausbessern.

**Comment by ThimoHoelter** [comment]
14. PathoFinding Example muss angepasst werden.

**Comment by ThomasDeBe** [comment]
Abgehakt, weil in einzelne Tickets aufgespalten
