### ISSUE TITLE
Beobachtungsabschnitt Proben/Technische Bearbeitung bisher nur als BackboneElement

### ISSUE THREAD

**Issue by ByteGnome** [medizininformatik-initiative/kerndatensatzmodul-PathologieBefund#30]
Eine Referenz auf die Probegewinnung und -bearbeitung ist zur Zeit nur über Specimen.collection / .processing möglich und somit nicht einzeln referenzierbar. Soll die Composition.section hier nur auf Specimen verweisen oder ist es erwünscht die .collection.method und .processing.procedure auch als einzelne Instanzen zu haben? 
![image](https://user-images.githubusercontent.com/7814403/143030707-11a82389-9161-4a82-95a1-a6d3b041ff93.png)

**Comment by patrick-werner** [comment]
Diese Elemente können direkt dem Specimen hinzugefügt werden.

**Comment by ByteGnome** [comment]
Wenn ich das richtig verstehen kann es also so bleiben wie bisher und die Composition verweist auf die Specimen Ressource in der section.

**Comment by patrick-werner** [comment]
Die Observations verweisen auf das Specimen, die Composition muss das nicht.
