### ISSUE TITLE
Beobachtungsabschnitt "Diagnostische Schlussfolgerung" - Reference(DiagReport)

### ISSUE THREAD

**Issue by ByteGnome** [medizininformatik-initiative/kerndatensatzmodul-PathologieBefund#33]
Die "Diagnostische Schlussfolgerung" wird aktuell mittels DiagnosticReport.conclusion / .conclusionCode abgebildet. Auch die Referenzen auf die jeweiligen Bilder und Observations wären über das Profil [PathologyReport](https://simplifier.net/medizininformatikinitiative-modulpathologie/pathologyreport) enthalten. Wäre somit der Abschnitt "Diagnostische Schlussfolgerung" vollständig, wenn die Referenz zum PathologyReport hergestellt wird? (+ .text für Narrative)

**Comment by patrick-werner** [comment]
DiagnosticReport.conclusion / .conclusionCode  wurde akzeptiert
