### ISSUE TITLE
Fragestellung als ServiceRequest.reasonCode?

### ISSUE THREAD

**Issue by ByteGnome** [medizininformatik-initiative/kerndatensatzmodul-PathologieBefund#34]
Wenn die Fragestellung als Datenelement verfügbar ist, ist diese auch nur über die ServiceRequest auffindbar und nicht als einzelne Instanz referenzierbar. Um die Fragestellung über das Document erreichen zu können, müsste die komplette ServiceRequest referenziert werden im Abschnitt "Klinische Informationen". Wäre das so auch in Ordnung oder ist es erwünscht hier jeweils einzelne Instanzen zu haben die referenziert werden?

**Comment by patrick-werner** [comment]
Der ServiceRequest wird über den DiagnosticReport und die Observations verlinkt. Ist dies nicht ausreichend?
