### ISSUE TITLE
Sollen die Abschnitte mehrere Bilddaten referenzieren können?

### ISSUE THREAD

**Issue by ByteGnome** [medizininformatik-initiative/kerndatensatzmodul-PathologieBefund#35]
Hintergrund der Frage ist, dass die Composition.section ein Datenelement .focus mit einer max. Kardinalität von 1 hat, welches aber vom Scope her zur Referenz auf die Bilddaten passen könnte. Der aktuelle Lösungsvorschlag geht über Unter-Abschnitte zu den einzelnen Sections, welche dann die eingebetteten Bilder als entry haben.

**Comment by Kosmos3** [comment]
Laut Pathologen ist es möglich, dass zu einer Observation mehrer Bilder gehören.  Lösungsvorschlag wurde akzeptiert.

**Comment by patrick-werner** [comment]
siehe auch #37
