### ISSUE TITLE
[SIMPLIFIER#1876] Fehlende Grouper im Beispiel

### ISSUE THREAD

**Issue by ByteGnome** [medizininformatik-initiative/kerndatensatzmodul-PathologieBefund#61]
[Issue#1876](https://simplifier.net/medizininformatikinitiative-modulpathologie/reportexample/~issues/1876)
> Gunter Haroske
> Im Beispiel fehlt offenbar eine Zwischenebene (die mit der Grouper Funktion): MacroscopicObservation, MicroscopicObservation etc, wie in den Profilen hinterlegt. Erst innerhalb dieser Observtions kommen die atomaren Results, wie z.B. Observation/MacroTumorSizeDim1, die als derivedFrom oder als hasMember Konstrukte gruppiert sind.
Es braucht in diesen Grouper-Observations auf jeden Fall auch ein Narrativ, nämlich den lesbaren Text der entsprechenden Sections.

Wir hatten in der letzten Telko ja über die Kadinalitäten der .result Slices gesprochen, konkret ging's da um all die Slices mit einer 0..1 Kardinalität. Da hieß es, dass es z.B. sein könnte, dass wir mehrere makroskopische Beobachtungen haben, was ja auch Sinn ergibt. Nun wäre meine Frage aber, wenn wir diese Zwischenebene mit der "Grouper-Fkt" haben, warum haben wir nochmal die Kardinalität bei .result auf 0..* hochgesetzt? Wenn es eine Grouper-Ebene geben würde, dann würde man doch eh z.B. alle MakroObservations zusammenführen und würde von .result aus nur auf die Grouper-Ebene verweisen. Und noch wichtiger, wenn wir die einzelnen Observations, nach ihrem Code den einzelnen "Section-Typen" zuordnen können, braucht man denn unbedingt diese Grouper-Ebene? Diese ist doch schon implizit gegeben durch Observation.code oder nicht? 
Wenn es um den Narrative Teil geht, haben wir doch über die Components ja die Möglichkeit Text und Werte zusammen in einer Observation zu erfassen. Vllt hab ich auch noch ein Brett vorm Kopf, oder es liegt daran, dass wir schon Freitag haben, aber ich verstehe nicht so ganz den Sinn dahinter so eine Grouper-Ebene konkret einzuführen.

**Comment by ByteGnome** [comment]
Ich assigne erstmal niemanden, weil wir ja über die Assignments eher bestimmen wer woran arbeitet, wäre aber ganz lieb, wenn ihr euch das mal anschauen würdet @patrick-werner @ThimoHoelter @Kosmos3. Kann aber natürlich bis Montag warten :)

**Comment by ThimoHoelter** [comment]
Benötigt man eventuell die Grouper-Funktion sobald es nicht nur mehrere makroskopischen Beobachtungen gibt, sondern auch mindestens eine weitere nicht makroskopische Beobachtung, um diese dann zu bündeln und mit .result 0..* zu referenzieren?

**Comment by ByteGnome** [comment]
aber wenn eine nicht-makroskopische kommt, dann wird sie ja nicht zu .result[macro-obs] gehören denk ich :/

**Comment by ByteGnome** [comment]
Update: Habe erstmal ein Grouper-Beispiel eingebaut. Ähnlich aufgebaut wie das APSR-FHIR Beispiel aus dem SharePoint. Issue würde ich gleich mit dem Commit davon erstmal schließen.
