### ISSUE TITLE
Update Information Organizer

### ISSUE THREAD

**Issue by ByteGnome** [medizininformatik-initiative/kerndatensatzmodul-PathologieBefund#75]
Es wäre noch zu klären wie die Versionierung beim Pathologiebefund zu regeln wäre. Bisherige Anforderungen/Ideen:
- Version soll sich erst ändern wenn es auch inhaltliche Änderungen am Befund gegeben hat (minimale (technische) Änderungen, sollen die Version nicht beeinflussen können). Dafür ist die Extension [versionNumber](http://hl7.org/fhir/R4/extension-composition-clinicaldocument-versionnumber.html) vorgeschlagen worden. 
- Informationen ähnlich wie im [UpdateInformationOrganizer](https://art-decor.org/art-decor/decor-templates--psr-?section=templates&id=1.3.6.1.4.1.19376.1.3.10.4.5&effectiveDate=2017-11-14T15:22:14&language=en-US) dokumentieren. Ginge das anhand der Versionnummer? (s. https://semver.org/)

**Comment by ThomasDeBe** [comment]
MII hat mittlerweile auf Calver Umgestellt, die nächste Version wird vsl. v2026
