### ISSUE TITLE
Zusätzliche Generische pathologisch-anatomische Einzelbeobachtung

### ISSUE THREAD

**Issue by ThimoHoelter** [medizininformatik-initiative/kerndatensatzmodul-PathologieBefund#77]
Die zusätzliche Generische pathologisch-anatomische Einzelbeobachtung auf ArtDecor als Mapping zum PathologyFinding muss noch geklärt werden.

**Comment by ThomasDeBe** [comment]
Ist schon mit drin. Case closed!

**Comment by gharoske** [comment]
Wo kann ich den Bezug finden?

Viele Grüße

Gunter Haroske
